// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"time"
)

type Director struct {
	ID        int64     `json:"id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Oscars    int64     `json:"oscars"`
	CreatedAt time.Time `json:"created_at"`
}

type Movie struct {
	ID         int64     `json:"id"`
	Title      string    `json:"title"`
	DirectorID int64     `json:"director_id"`
	Rating     string    `json:"rating"`
	Poster     string    `json:"poster"`
	CreatedAt  time.Time `json:"created_at"`
}

type Ticket struct {
	ID          int64     `json:"id"`
	MovieID     int64     `json:"movie_id"`
	TicketOwner string    `json:"ticket_owner"`
	Child       int16     `json:"child"`
	Adult       int16     `json:"adult"`
	Total       int64     `json:"total"`
	CreatedAt   time.Time `json:"created_at"`
}

type User struct {
	Username       string    `json:"username"`
	HashedPassword string    `json:"hashed_password"`
	Email          string    `json:"email"`
	AccessLevel    int16     `json:"access_level"`
	CreatedAt      time.Time `json:"created_at"`
}
