// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	CreateDirector(ctx context.Context, arg CreateDirectorParams) (Director, error)
	CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error)
	CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteMovie(ctx context.Context, id int64) error
	DeleteTickets(ctx context.Context, id int64) error
	GetDirector(ctx context.Context, id int64) (Director, error)
	GetMovie(ctx context.Context, id int64) (Movie, error)
	GetTicket(ctx context.Context, id int64) (Ticket, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListDirectors(ctx context.Context, arg ListDirectorsParams) ([]Director, error)
	ListMovies(ctx context.Context) ([]Movie, error)
	ListTickets(ctx context.Context, arg ListTicketsParams) ([]Ticket, error)
}

var _ Querier = (*Queries)(nil)
